version: '3.8'

services:
  api:
    build: .
    container_name: api-automatica
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DB_HOST=db 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    depends_on:
      - db
      - migrations  

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}               
      MYSQL_USER: ${DB_USER}                   
      MYSQL_PASSWORD: ${DB_PASSWORD}           
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

  migrations:
    build: .
    container_name: migrations
    environment:
      - DB_HOST=db 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    command: ["npm", "run", "migrate"]
    restart: "no"  

volumes:
  mysql-data:
